update

diff --git a/push b/push
--- a/push
+++ b/push
@@ -6,24 +6,27 @@ repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
 remote_name="origin"
 main_branch="master"
 target_branch="master"
-build_dir="dist"
 
 cd "$GITHUB_WORKSPACE"
 
 git config user.name "$GITHUB_ACTOR"
 git config user.email "${GITHUB_ACTOR}@bots.github.com"
 
-git checkout "$target_branch"
-git rebase "${remote_name}/${main_branch}"
 npm install node-fetch
 node ec2.js
-git add data.json 
 
-git commit -m "updated GitHub data"
-if [ $? -ne 0 ]; then
-    echo "nothing to commit"
-    exit 0
+git add data.json
+set +e  # Grep succeeds with nonzero exit codes to show results.
+git status | grep modified
+if [ $? -eq 0 ]
+then
+    set -e
+    git commit -am "data updated on - $(date)"
+    git push
+else
+    set -e
+    echo "No changes since last run"
 fi
 
-git remote set-url "$remote_name" "$repo_uri" # includes access token
-git push --force-with-lease "$remote_name" "$target_branch"
+echo "finish"
+
